version: '3'

tasks:
  build:
    desc: Build the crate with verbose output to debug
    cmds:
      - cmd: set RUSTFLAGS=-C link-args=/VERBOSE
      - cmd: cargo build -vvv
  clean-build:
    desc: Build the crate with verbose output to debug
    cmds:
      - cmd: set RUSTFLAGS=-C link-args=/VERBOSE
      - cmd: cargo clean
      - cmd: cargo build -vvv
  test:hdep:
    cmds:
      - cargo test --features hdep_tests